<a href="https://colab.research.google.com/github/IvanVoinovGitHub/Covid19-Analysis-Modeling/blob/main/PA-Aggregated-Data/PA_Covid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv
import pandas as pd

In [ ]:
#COVID-19 Aggregate Cases Current Daily County Health
url1 = "https://data.pa.gov/api/views/j72v-r42c/rows.csv?accessType=DOWNLOAD"
data1 = pd.read_csv(url1)

In [ ]:
#Data Cleaning for Aggregate Cases
data11 = data1.drop(["Latitude", "Georeferenced Lat & Long", "Longitude"], axis =1)
data11.rename(columns = {'County FIPS Code':'FIPS'}, inplace = True)
data11 = data11.rename(columns = {data11.columns[4] : 'Cum_cases'})
data11 = data11.dropna()
data11['Date'] = pd.to_datetime(data11['Date'])
data11['Date'] = data11['Date'].dt.strftime('%m/%d/%Y')
data11['Date'] = pd.to_datetime(data11['Date'])
#data11['Date'] = data11['Date'].dt.strftime('%m/%d/%Y')
print(data11.info())
data11.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52156 entries, 0 to 52631
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Jurisdiction                 52156 non-null  object
 1   Date                         52156 non-null  datetime64[ns]
 2   New Cases                    52156 non-null  int64
 3   7-day Average New Cases      52156 non-null  float64
 4   Cum_cases                    52156 non-null  int64
 5   Population (2019)            52156 non-null  int64
 6   New Case Rate                52156 non-null  float64
 7   7-Day Average New Case Rate  52156 non-null  float64
 8   Cumulative Case Rate         52156 non-null  float64
 9   FIPS                         52156 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(4), object(1)
memory usage: 4.4+ MB
None

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cum_cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,FIPS
0,Mifflin,2021-03-26,9,9.0,4787,46138,19.5,19.5,10375.4,42087
1,Juniata,2021-09-29,14,13.4,2661,24763,56.5,54.2,10745.9,42067
2,Warren,2022-01-13,70,43.0,6158,39191,178.6,109.7,15712.8,42123
3,Columbia,2022-02-18,21,23.0,14750,64964,32.3,35.4,22704.9,42037
4,Columbia,2022-01-17,89,116.7,12813,64964,137.0,179.7,19723.2,42037
5,Elk,2021-12-07,15,15.0,4948,29910,50.2,50.2,16543.0,42047
6,Juniata,2021-05-04,3,3.3,2096,24763,12.1,13.3,8464.2,42067
7,Elk,2021-02-02,6,10.7,2168,29910,20.1,35.8,7248.4,42047
8,Juniata,2021-09-17,10,9.7,2500,24763,40.4,39.2,10095.7,42067
9,Warren,2021-11-21,3,35.6,4822,39191,7.7,90.8,12303.8,42123

In [ ]:
#United States COVID-19 County Level of Community Transmission as Originally Posted
url2 = "https://data.cdc.gov/api/views/8396-v7yb/rows.csv?accessType=DOWNLOAD"
data2 = pd.read_csv(url2)

In [ ]:
#Data Cleaning for Community Transmission Level 
data22 = data2.query('state_name == "Pennsylvania"')
data22 = data22.drop(["cases_per_100K_7_day_count_change", "state_name", "county_name"], axis = 1)
data22.rename(columns = {'fips_code':'FIPS', 'report_date': 'Date'}, inplace = True)
data22 = data22.dropna()
data22['Date'] = pd.to_datetime(data22['Date'])
data22['Date'] = data22['Date'].dt.strftime('%m/%d/%Y')
data22['Date'] = pd.to_datetime(data22['Date'])
print(data22.info())
data22.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15946 entries, 6 to 772591
Data columns (total 4 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   FIPS                                                15946 non-null  int64
 1   Date                                                15946 non-null  datetime64[ns]
 2   percent_test_results_reported_positive_last_7_days  15946 non-null  float64
 3   community_transmission_level                        15946 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 622.9+ KB
None

,FIPS,Date,percent_test_results_reported_positive_last_7_days,community_transmission_level
6,42039,2021-08-16,7.88,substantial
11,42025,2021-08-16,4.95,high
45,42035,2021-08-19,11.72,high
88,42085,2021-08-23,8.57,high
129,42017,2021-08-26,6.41,high
133,42117,2021-08-26,8.59,substantial
145,42099,2021-08-27,14.56,high
173,42071,2021-08-29,10.43,high
286,42013,2021-09-07,7.46,high
297,42089,2021-09-07,13.63,high

In [ ]:
#COVID-19 Vaccinations in the United States,Jurisdiction
url3 = "https://data.cdc.gov/api/views/unsk-b7fc/rows.csv?accessType=DOWNLOAD"
data3 = pd.read_csv(url3)

In [ ]:
data33 = data3.query('Location == "PA"')
data33 = data33.drop(["MMWR_week", "Distributed_Janssen", "Distributed_Moderna", "Distributed_Pfizer", "Distributed_Unk_Manuf", "Dist_Per_100K", "Distributed_Per_100k_12Plus", "Distributed_Per_100k_18Plus", "Distributed_Per_100k_65Plus", "Administered_12Plus", "Administered_18Plus", "Administered_65Plus", "Administered_Janssen", "Administered_Moderna", "Administered_Pfizer", "Administered_Unk_Manuf", "Admin_Per_100K", "Admin_Per_100k_12Plus", "Admin_Per_100k_18Plus", "Admin_Per_100k_65Plus", "Recip_Administered", "Administered_Dose1_Recip_12Plus", "Administered_Dose1_Recip_12PlusPop_Pct", "Administered_Dose1_Recip_18Plus", "Administered_Dose1_Recip_18PlusPop_Pct", "Administered_Dose1_Recip_65Plus", "Administered_Dose1_Recip_65PlusPop_Pct", "Series_Complete_12Plus", "Series_Complete_12PlusPop_Pct", "Series_Complete_18Plus", "Series_Complete_18PlusPop_Pct", "Series_Complete_65Plus", "Series_Complete_65PlusPop_Pct", "Series_Complete_Janssen", "Series_Complete_Moderna", "Series_Complete_Pfizer", "Series_Complete_Unk_Manuf", "Series_Complete_Janssen_12Plus", "Series_Complete_Moderna_12Plus", "Series_Complete_Pfizer_12Plus", "Series_Complete_Unk_Manuf_12Plus", "Series_Complete_Janssen_18Plus", "Series_Complete_Moderna_18Plus", "Series_Complete_Pfizer_18Plus", "Series_Complete_Unk_Manuf_18Plus", "Series_Complete_Janssen_65Plus", "Series_Complete_Moderna_65Plus", "Series_Complete_Pfizer_65Plus", "Series_Complete_Unk_Manuf_65Plus", "Additional_Doses_12Plus", "Additional_Doses_12Plus_Vax_Pct", "Additional_Doses_18Plus", "Additional_Doses_18Plus_Vax_Pct", "Additional_Doses_50Plus", "Additional_Doses_50Plus_Vax_Pct", "Additional_Doses_65Plus", "Additional_Doses_65Plus_Vax_Pct", "Additional_Doses_Moderna", "Additional_Doses_Pfizer", "Additional_Doses_Janssen", "Additional_Doses_Unk_Manuf", "Administered_Dose1_Recip_5Plus", "Administered_Dose1_Recip_5PlusPop_Pct", "Series_Complete_5Plus", "Series_Complete_5PlusPop_Pct", "Administered_5Plus", "Admin_Per_100k_5Plus", "Series_Complete_Moderna_5Plus", "Series_Complete_Pfizer_5Plus", "Series_Complete_Janssen_5Plus", "Series_Complete_Unk_Manuf_5Plus"], axis =1)
data33['Date'] = pd.to_datetime(data33['Date'])
data33['Date'] = data33['Date'].dt.strftime('%m/%d/%Y')
data33['Date'] = pd.to_datetime(data33['Date'])
data33 = data33.drop('Location', axis =1)
print(data33.info())
data33.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 486 entries, 29 to 31377
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        486 non-null    datetime64[ns]
 1   Distributed                 486 non-null    int64
 2   Administered                486 non-null    int64
 3   Administered_Dose1_Recip    486 non-null    int64
 4   Administered_Dose1_Pop_Pct  486 non-null    float64
 5   Series_Complete_Yes         486 non-null    int64
 6   Series_Complete_Pop_Pct     486 non-null    float64
 7   Additional_Doses            234 non-null    float64
 8   Additional_Doses_Vax_Pct    481 non-null    float64
 9   Distributed_Per_100k_5Plus  479 non-null    float64
dtypes: datetime64[ns](1), float64(5), int64(4)
memory usage: 41.8 KB
None

,Date,Distributed,Administered,Administered_Dose1_Recip,Administered_Dose1_Pop_Pct,Series_Complete_Yes,Series_Complete_Pop_Pct,Additional_Doses,Additional_Doses_Vax_Pct,Distributed_Per_100k_5Plus
29,2022-04-13,29939625,22528100,10806953,84.4,8701030,68.0,3673627.0,42.2,247352.0
79,2022-04-12,29905425,22495403,10797793,84.3,8694354,67.9,3664492.0,42.1,247069.0
142,2022-04-11,29882325,22487636,10795308,84.3,8691454,67.9,3662170.0,42.1,246878.0
255,2022-04-10,29882325,22482965,10793827,84.3,8689783,67.9,3660680.0,42.1,246878.0
314,2022-04-09,29795825,22472518,10790873,84.3,8686408,67.9,3657197.0,42.1,246164.0
328,2022-04-08,29795825,22457550,10785831,84.3,8682027,67.8,3652318.0,42.1,246164.0
399,2022-04-07,29708725,22446301,10782644,84.2,8678318,67.8,3648557.0,42.0,245444.0
475,2022-04-06,29665125,22431687,10778370,84.2,8673652,67.8,3644256.0,42.0,245084.0
538,2022-04-05,29619525,22414957,10773907,84.2,8669022,67.7,3639624.0,42.0,244707.0
602,2022-04-04,29582725,22410183,10772049,84.1,8667207,67.7,3637939.0,42.0,244403.0

In [ ]:
#Merge First Two Data Tables
final_data1 = pd.merge(left = data11, right = data22, how = 'outer', on = ['FIPS', 'Date'])
final_data1 = final_data1.sort_values(by='Jurisdiction') 
final_data1 = final_data1.dropna()
final_data = pd.merge(left = final_data1, right = data33, how = 'outer', on = 'Date')
final_data = final_data.dropna()
final_data = final_data.drop("Distributed_Per_100k_5Plus", axis = 1)
final_data.sort_values(by=['Jurisdiction', 'Date'])
final_data = final_data.drop(["Jurisdiction", "FIPS"], axis = 1)

#Change the transmission levels
final_data = final_data.replace(['low'], 0)
final_data = final_data.replace(['moderate'], 1)
final_data = final_data.replace(['substantial'], 2)
final_data = final_data.replace(['high'], 3)


final_data = final_data.groupby('Date').agg({
    'New Cases' : 'sum',
    '7-day Average New Cases' : 'sum',
    'Cum_cases' : 'sum',
    'Population (2019)' : 'sum',
    'New Case Rate' : 'sum',
    '7-Day Average New Case Rate' : 'sum',
    'Cumulative Case Rate' : 'sum',
    'percent_test_results_reported_positive_last_7_days' : 'mean',
    'community_transmission_level' : 'max',
    'Distributed' : 'mean',
    'Administered' : 'mean',
    'Administered_Dose1_Recip' : 'mean',
    'Administered_Dose1_Pop_Pct' : 'mean',
    'Series_Complete_Yes' : 'mean',
    'Series_Complete_Pop_Pct' : 'mean',
    'Additional_Doses' : 'mean',
    'Additional_Doses_Vax_Pct' : 'mean'
})

In [ ]:
final_data.head(10)

,New Cases,7-day Average New Cases,Cum_cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,percent_test_results_reported_positive_last_7_days,community_transmission_level,Distributed,Administered,Administered_Dose1_Recip,Administered_Dose1_Pop_Pct,Series_Complete_Yes,Series_Complete_Pop_Pct,Additional_Doses,Additional_Doses_Vax_Pct
Date,,,,,,,,,,,,,,,,,
2021-08-23,3085.0,2657.6,1288451.0,12801989.0,1691.8,1335.8,673519.4,7.788507,3,17370885.0,15172755.0,8756622.0,68.4,6954691.0,54.3,0.0,0.0
2021-08-24,3692.0,2865.8,1292143.0,12801989.0,1913.3,1446.7,675433.3,8.070000,3,17370885.0,15190103.0,8766124.0,68.5,6962263.0,54.4,0.0,0.0
2021-08-25,3248.0,2764.2,1295391.0,12801989.0,1650.1,1411.5,677083.0,8.288060,3,17421485.0,15218928.0,8781535.0,68.6,6974946.0,54.5,0.0,0.0
2021-08-26,3966.0,2972.8,1299357.0,12801989.0,2258.5,1564.4,679341.5,8.549403,3,17625235.0,15253030.0,8799978.0,68.7,6989211.0,54.6,0.0,0.0
2021-08-27,3858.0,3123.1,1303215.0,12801989.0,2005.5,1647.5,681347.4,9.145672,3,17739485.0,15292961.0,8822710.0,68.9,7004761.0,54.7,0.0,0.0
2021-08-28,2588.0,3180.2,1305803.0,12801989.0,1328.0,1678.0,682675.5,9.677463,3,17806425.0,15331833.0,8842653.0,69.1,7022532.0,54.9,0.0,0.0
2021-08-29,2540.0,3282.1,1308343.0,12801989.0,1328.2,1739.7,684002.8,10.093731,3,17818045.0,15365996.0,8860352.0,69.2,7037389.0,55.0,0.0,0.0
2021-08-30,3578.0,3353.1,1311921.0,12801989.0,2168.7,1807.5,686172.0,10.176866,3,17818045.0,15388826.0,8872244.0,69.3,7047739.0,55.1,0.0,0.0
2021-08-31,3933.0,3387.3,1315854.0,12801989.0,2319.1,1865.4,688491.0,10.262985,3,17853915.0,15403600.0,8880224.0,69.4,7054540.0,55.1,0.0,0.0
2021-09-01,3729.0,3455.8,1319583.0,12801989.0,2062.1,1924.3,690553.2,10.500597,3,17916445.0,15439653.0,8897546.0,69.5,7071957.0,55.2,0.0,0.0

In [ ]:
print(final_data.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 219 entries, 2021-08-23 to 2022-04-13
Data columns (total 17 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   New Cases                                           219 non-null    float64
 1   7-day Average New Cases                             219 non-null    float64
 2   Cum_cases                                           219 non-null    float64
 3   Population (2019)                                   219 non-null    float64
 4   New Case Rate                                       219 non-null    float64
 5   7-Day Average New Case Rate                         219 non-null    float64
 6   Cumulative Case Rate                                219 non-null    float64
 7   percent_test_results_reported_positive_last_7_days  219 non-null    float64
 8   community_transmission_level                        219 non-null    int64
 9   Distributed                                         219 non-null    float64
 10  Administered                                        219 non-null    float64
 11  Administered_Dose1_Recip                            219 non-null    float64
 12  Administered_Dose1_Pop_Pct                          219 non-null    float64
 13  Series_Complete_Yes                                 219 non-null    float64
 14  Series_Complete_Pop_Pct                             219 non-null    float64
 15  Additional_Doses                                    219 non-null    float64
 16  Additional_Doses_Vax_Pct                            219 non-null    float64
dtypes: float64(16), int64(1)
memory usage: 30.8 KB
None